Message queue docs
OpenZeppelin/polkadot-runtime-template pull request #58
Opened 2023-12-12 14:45 UTC by ozgunozerk

Related to #15 (after xcmp queue docs, the issue will be completely closed)

- [x] Documentation

2023-12-12 14:47 UTC, ozgunozerk commented
Message queue does not changed between v1.3.0 and v1.5.0. 
So even if we decide for or against v1.3.0, it doesn't matter :)

2023-12-12 15:40 UTC, ozgunozerk commented on docs/modules/ROOT/pages/pallets/message-queue.adoc
> +due to being overweight.
i liked yours better! thanks

2023-12-13 06:45 UTC, KitHat commented
Could you please add a link to `docs/modules/ROOT/nav.adoc`?

2023-12-13 08:49 UTC, KitHat requested changes
Content looks good to me, but we need to fix some formatting IMO

2023-12-13 08:49 UTC, KitHat commented on docs/modules/ROOT/pages/pallets/message-queue.adoc
> +
Looks like something went wrong with the formatting there
It is just a plain wall of text: https://deploy-preview-58--docs-oz-polkadot.netlify.app/substrate-runtimes/0.1.0/pallets/message-queue#important_mentions_and_faqs

2023-12-13 11:44 UTC, KitHat approved these changes

2023-12-13 11:44 UTC, merged