multisig docs
OpenZeppelin/polkadot-runtime-template pull request #64
Opened 2023-12-15 15:44 UTC by ozgunozerk

2023-12-15 15:49 UTC, ozgunozerk commented
Will put to chatgpt before merging, do not spend much time on the English :)

2023-12-15 20:32 UTC, ozgunozerk commented
Haha sure! Used grammarly this time

2023-12-16 11:01 UTC, ozgunozerk commented on docs/modules/ROOT/pages/pallets/multisig.adoc
> +Payment: `DepositBase` will be reserved if this is the first approval, plus `threshold` times `DepositFactor`. It is returned once this dispatch happens or is canceled.
makes sense, I'll switch to `cancelled`, I think it's 90% chance that OZ is following American English

2023-12-16 11:05 UTC, ozgunozerk commented on docs/modules/ROOT/pages/pallets/multisig.adoc
> +This module enables multi-signature operations in your runtime. It allows multiple signed origins (accounts) to coordinate and dispatch a call. For the call to execute, the threshold number of accoun
> Are all signed origins accounts? In other words does there exist any signed origin that is not an account?

Yes, all signed origins are accounts, and no, there does not exist any signed origin that is not an account. 

The reason for this: `It allows multiple signed origins (accounts)` was to make it clear to end developer that, the parameter `origin` represents `accounts` in this context. I think the explanation should stay as is, but if you have a strong preference on committing your suggestion, we can do so 👍

2023-12-16 11:08 UTC, ozgunozerk commented on docs/modules/ROOT/pages/pallets/multisig.adoc
> +This module enables multi-signature operations in your runtime. It allows multiple signed origins (accounts) to coordinate and dispatch a call. For the call to execute, the threshold number of accoun
> And is a multisig an account? So can a multisig be one of the accounts in another multisig?

`multisig` refers to the operation itself (along with threshold, accounts, call, everything). But if you meant to ask, can a multiple account be a part of another multisig operation, then the answer is yes!

So, a multisig account: X -> composed of A,B,C
where A is also a multisig account, and composed of: A1, A2, A3
is completely possible :)

2023-12-18 10:18 UTC, KitHat requested changes
Two small comments, in other things, LGTM

2023-12-18 10:19 UTC, KitHat commented on docs/modules/ROOT/pages/pallets/multisig.adoc
> += Pallet Name
Please, update the pallet name 🙂

2023-12-18 10:20 UTC, ozgunozerk commented on docs/modules/ROOT/pages/pallets/multisig.adoc
> +Branch/Release: `release-polkadot-v{1.3.0}`
ah yeah, that was the from template... Fixing

2023-12-18 11:12 UTC, KitHat approved these changes
Lgtm

2023-12-18 11:12 UTC, merged